files:
    train_set: C:/Users/motibz/Documents/Studing/Cancer_Data_Mining/data_sets/02_18_train/02_18_train/best_fixed_train.csv
#    test_set: C:/Users/motibz/Documents/Studing/Cancer_Data_Mining/data_sets/02_18_train/02_18_train/one_row_test.csv
    test_set: C:/Users/motibz/Documents/Studing/Cancer_Data_Mining/data_sets/02_18_train/02_18_train/spit_fixed.csv

#from this list: http://scikit-learn.org/stable/modules/model_evaluation.html
score: roc_auc

outputs:
  show_charts: True
  save_models_agenda: best # all/best/none
  outdir: C:/Users/motibz/Documents/Studing/

#TODO
# http://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
models:
  -AdaBoostClassifier
  -BaggingClassifier
  -BayesianGaussianMixture
  -BernoulliNB
  -CalibratedClassifierCV
  -DPGMM
  -DecisionTreeClassifier
  -ExtraTreeClassifier
  -ExtraTreesClassifier
  -GMM
  -GaussianMixture
  -GaussianNB
  -GaussianProcessClassifier
  -GradientBoostingClassifier
  -KNeighborsClassifier
  -LabelPropagation
  -LabelSpreading
  -LinearDiscriminantAnalysis
  -LogisticRegression
  -LogisticRegressionCV
  -MLPClassifier
  -MultinomialNB
  -NuSVC
  -QuadraticDiscriminantAnalysis
  -RandomForestClassifier
  -SGDClassifier
  -SVC
  -VBGMM

