files:
    # Here you should put the path to the csv files, if you don't have test set keep the field empty
    train_set: C:/Users/motibz/Documents/Studing/Cancer_Data_Mining/data_sets/02_18_train/02_18_train/spit-50.csv
    test_set:

#Choose the scoring method (from this list: http://scikit-learn.org/stable/modules/model_evaluation.html)
score: roc_auc

#The cross validation process works with 10 folds, you can choose the number of the Crose validation process for each data set
cv_loops: 100

# TODO
fs_function:

outputs:
  #Showing the charts during the process
  show_charts: False
  #Save the charts (image)
  save_charts: True
  #Save the stduot (for debuging)
  save_stdout: True
  #Save the traind model binary file (for the UI system)
  save_models_agenda: all # all/best/none
  #The out dir for all of the outputs (if not exist will be created)
  outdir: C:/Users/motibz/Documents/Studing/spit-50_f_class_if_auc

#TODO - Not implemented
# http://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
models:
  -AdaBoostClassifier
  -BaggingClassifier
  -BayesianGaussianMixture
  -BernoulliNB
  -CalibratedClassifierCV
  -DPGMM
  -DecisionTreeClassifier
  -ExtraTreeClassifier
  -ExtraTreesClassifier
  -GMM
  -GaussianMixture
  -GaussianNB
  -GaussianProcessClassifier
  -GradientBoostingClassifier
  -KNeighborsClassifier
  -LabelPropagation
  -LabelSpreading
  -LinearDiscriminantAnalysis
  -LogisticRegression
  -LogisticRegressionCV
  -MLPClassifier
  -MultinomialNB
  -NuSVC
  -QuadraticDiscriminantAnalysis
  -RandomForestClassifier
  -SGDClassifier
  -SVC
  -VBGMM

