files:
#    train_set: C:/Users/motibz/Documents/Studing/Cancer_Data_Mining/data_sets/02_18_train/02_18_train/best_alone.csv
#    test_set:
    train_set: C:/Users/motibz/Documents/Studing/Cancer_Data_Mining/data_sets/02_18_train/02_18_train/best_fixed(1).csv
    test_set: C:/Users/motibz/Documents/Studing/Cancer_Data_Mining/data_sets/02_18_train/02_18_train/spit_fixed(1).csv

#from this list: http://scikit-learn.org/stable/modules/model_evaluation.html
score: roc_auc

outputs:
  show_charts: False
  save_models_agenda: all # all/best/none
  outdir: C:/Users/motibz/Documents/Studing/

#TODO
# http://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
models:
  -AdaBoostClassifier
  -BaggingClassifier
  -BayesianGaussianMixture
  -BernoulliNB
  -CalibratedClassifierCV
  -DPGMM
  -DecisionTreeClassifier
  -ExtraTreeClassifier
  -ExtraTreesClassifier
  -GMM
  -GaussianMixture
  -GaussianNB
  -GaussianProcessClassifier
  -GradientBoostingClassifier
  -KNeighborsClassifier
  -LabelPropagation
  -LabelSpreading
  -LinearDiscriminantAnalysis
  -LogisticRegression
  -LogisticRegressionCV
  -MLPClassifier
  -MultinomialNB
  -NuSVC
  -QuadraticDiscriminantAnalysis
  -RandomForestClassifier
  -SGDClassifier
  -SVC
  -VBGMM

