files:
    train_set: C:/Users/motibz/Documents/Studing/Cancer_Data_Mining/data_sets/02_18_train/02_18_train/BEST_my_changes_train.csv
    test_set:

#from this list: http://scikit-learn.org/stable/modules/model_evaluation.html
score: accuracy

#from this list:
#TODO
models:
  - first
  - second
